const projects = [
 {image:'stairs.png',name:'C&M',number:'03/12',alt:'Escalier courbe en bois, balustres et murs de brique'},
 {image:'facade.png',name:'Projet Sainte-Chose',number:'07/10',alt:'Maison de brique rouge dans un jardin automnal'},
 {image:'residence.png',name:'Résidence XYZ',number:'02/06',alt:'Enfilade de pièces lumineuses, parquet et murs de brique'},
 {image:'maison.png',name:'Maison Casa Home',number:'11/14',alt:'Intérieur avec escalier, colonnes claires et menuiserie en bois'},
 {image:'brick.png',name:'Projet Sainte-Chose',number:'04/10',alt:'Détail d’une façade en briques saillantes'}
];
const entries=Array.from({length:33},()=>({slide:0,name:'475 Grande-Allée, Qc',type:'Résidentiel',status:'Complété',start:'2021',end:'2025'}));
const thumbs=[{image:'stairs.png',slide:0,alt:'Escalier courbe en bois, balustres et murs de brique'},{image:'facade.png',slide:1,alt:'Maison de brique rouge dans un jardin automnal'},{image:'survol-2.jpg',y:'10%',alt:'Rangée de maisons victoriennes'},{image:'survol-3.png',alt:'Axonométrie éclatée en noir et blanc'},{image:'residence.png',slide:2,alt:'Enfilade de pièces lumineuses, parquet et murs de brique'},{image:'survol-5.jpg',alt:'Bâtiment vitré à structure rouge parmi les arbres'},{image:'survol-6.jpg',y:'53.5%',alt:'Escalier extérieur dans la verdure'},{image:'survol-7.jpg',alt:'Intérieur blanc, porte et fenêtre'}];
const slides=document.querySelector('.slides');
projects.forEach((p,i)=>{const img=document.createElement('img');img.className='slide';img.src='assets/'+p.image;img.alt=p.alt;img.decoding='async';if(i===0)img.fetchPriority='high';slides.append(img)});
let current=0,timer=null,page='accueil';
function head(){const h=document.querySelector('header');h.hidden=page==='accueil';h.classList.toggle('always',page==='index'||page==='survol')}
function menu(o){document.querySelector('header').classList.toggle('open',o);document.querySelector('.mark').setAttribute('aria-expanded',String(o))}
document.querySelector('.mark').onclick=()=>menu(!document.querySelector('header').classList.contains('open'));
function sync(){document.querySelectorAll('.slide').forEach((el,j)=>el.setAttribute('aria-hidden',String(j!==current)));document.querySelector('#image-number').textContent=projects[current].number;document.querySelector('#project-name').textContent=projects[current].name;document.querySelector('#position').textContent=String(current+1).padStart(2,'0')+' / 05';head()}
function show(i,smooth=true){current=(i+projects.length)%projects.length;slides.scrollTo({left:current*slides.clientWidth,behavior:smooth?'smooth':'instant'});sync()}
const seen=new IntersectionObserver(es=>es.forEach(e=>{const j=[...slides.children].indexOf(e.target);if(e.isIntersecting&&j!==current){current=j;sync()}}),{root:slides,threshold:.5});[...slides.children].forEach(el=>seen.observe(el));
function stop(){clearInterval(timer);timer=null;document.querySelector('#play').textContent='Lecture';document.querySelector('#play').setAttribute('aria-label','Lancer le diaporama')}
function step(d){stop();show(current+d)}
document.querySelector('#prev').onclick=()=>step(-1);document.querySelector('#next').onclick=()=>step(1);
function start(){if(timer)return;timer=setInterval(()=>show(current+1),2000);document.querySelector('#play').textContent='Pause';document.querySelector('#play').setAttribute('aria-label','Mettre le diaporama en pause')}
document.querySelector('#play').onclick=()=>timer?stop():start();
const tiles='40516273372615044051627337261504615043727726150405105151',flips='00000000111111110000000011111111111111110111111100000000';const grid=document.querySelector('.tiles'),counts=[],runs=[5,5,5,5,5,5,5,5,5,5,6],groups=runs.flatMap((n,g)=>Array(n).fill(g));[...tiles].forEach((t,n)=>{const p=thumbs[t],a=document.createElement('a'),k=groups[n],f=flips[n],c=counts[k]=(counts[k]||0)+1;a.href='#diaporama';a.dataset.project=k;a.innerHTML='<img src="assets/'+p.image+'" alt="'+p.alt+'" loading="lazy"><span class="tile-label" aria-hidden="true"><span>'+entries[k].name+'</span><span>'+String(c).padStart(2,'0')+'/<span class="total"></span></span></span>';if(f==='1')a.firstChild.style.transform='scaleX(-1)';if(p.y)a.firstChild.style.objectPosition='50% '+p.y;a.onclick=()=>{stop();show(p.slide||0)};a.onmouseenter=a.onfocus=()=>light(k);a.onmouseleave=a.onblur=()=>light(null);grid.append(a)});[...grid.children].forEach(a=>a.querySelector('.total').textContent=String(counts[a.dataset.project]).padStart(2,'0'));
function light(k){[...grid.children].forEach(a=>a.classList.toggle('lit',k!==null&&+a.dataset.project===k))}
const list=document.querySelector('.project-list'),preview=document.querySelector('.index-preview'),anchor=document.querySelector('.index-anchor'),all=document.querySelector('.expand-all'),wide=matchMedia('(min-width:701px)');let hovered=null;
function place(){if(hovered===null||!wide.matches){preview.style.visibility='hidden';return}const r=anchor.getBoundingClientRect();if(!r.width)return;const li=list.children[hovered],row=li.getBoundingClientRect(),h=r.width*390/520,down=li.querySelector('.name').getBoundingClientRect().top+3,top=down+h<=innerHeight?down:row.bottom-h>=0?row.bottom-h:0;Object.assign(preview.style,{left:r.left+'px',top:top+'px',width:r.width+'px',height:h+'px',visibility:'visible'})}
function hover(i){hovered=i;[...list.children].forEach((li,j)=>li.classList.toggle('active',j===i));if(i!==null)preview.firstChild.src='assets/'+projects[entries[i].slide].image;place()}
function expanded(){const n=list.querySelectorAll('.expanded').length===list.children.length;all.textContent=n?'Tout fermer':'Tout ouvrir';return n}
entries.forEach((p,n)=>{const i=p.slide,li=document.createElement('li');li.innerHTML='<a class="project-image" href="#diaporama"><img src="assets/'+projects[i].image+'" alt="'+projects[i].alt+'" loading="lazy"></a><a class="project-row index-cols" href="#diaporama"><span class="name">'+p.name+'</span><span>'+p.type+'</span><span>'+p.status+'</span><span>'+'<span class="from">'+p.start+'</span><span class="to">à</span>'+p.end+'</span></a>';const [pic,row]=li.children;pic.onclick=()=>{stop();show(i)};row.onclick=e=>{if(!wide.matches){e.preventDefault();li.classList.toggle('expanded');expanded();return}stop();show(i)};row.onmouseenter=row.onfocus=()=>hover(n);list.append(li)});
all.onclick=()=>{const n=expanded();[...list.children].forEach(li=>li.classList.toggle('expanded',!n));expanded()};window.addEventListener('scroll',place,{passive:true});window.addEventListener('resize',place);
function route(){page=location.hash.slice(1)||'accueil';if(!['accueil','diaporama','survol','index','bureau'].includes(page))page='accueil';document.querySelectorAll('main>section').forEach(el=>{el.hidden=el.id!==page;el.classList.remove('leaving')});head();menu(false);hover(page==='index'?0:null);document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});stop();if(page==='diaporama'){show(current,false);start()}window.scrollTo(0,0);document.title=(page==='accueil'?'Bureau Normal — Architecture':page.charAt(0).toUpperCase()+page.slice(1)+' — Bureau Normal')}
window.addEventListener('hashchange',route);window.addEventListener('scroll',()=>{const el=document.querySelector('#accueil');if(el.hidden||el.classList.contains('leaving')||scrollY<=0||innerHeight+scrollY<document.documentElement.scrollHeight-2)return;if(el.dataset.wait)return;el.dataset.wait=1;setTimeout(()=>{delete el.dataset.wait;if(el.hidden||innerHeight+scrollY<document.documentElement.scrollHeight-2)return;el.classList.add('leaving');setTimeout(()=>{if(!el.hidden)location.hash='diaporama'},1200)},700)},{passive:true});
document.addEventListener('keydown',e=>{if(e.key==='Escape')menu(false);if(document.querySelector('#diaporama').hidden||e.target.closest('button,a'))return;if(e.key==='ArrowRight'){e.preventDefault();step(1)}if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}});
let wheelAt=0;document.querySelector('#diaporama').addEventListener('wheel',e=>{e.preventDefault();const d=Math.abs(e.deltaX)>=Math.abs(e.deltaY)?e.deltaX:e.deltaY,now=Date.now();if(Math.abs(d)<15||now-wheelAt<800)return;wheelAt=now;const on=timer;show(current+(d>0?1:-1));if(on){stop();start()}},{passive:false});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});document.querySelectorAll('.year').forEach(el=>el.textContent=new Date().getFullYear());show(0);route();
